version: '3'
services:
  app-auction:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    command: sh -c "/auction"
    depends_on:
      - mongodb
    networks:
      - localNetwork
  mongodb:
    build: .docker/mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: auctions
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/dbdata:/data/db
    networks:
      - localNetwork

networks:
  localNetwork:
    driver: bridge