version: '3'
services:
  app-auction:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - cmd/auction/.env
    command: sh -c "/auction"
    depends_on:
      - mongodb
    networks:
      - localNetwork
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.docker/dbdata:/data/db
    networks:
      - localNetwork

  networks:
  localNetwork:
    driver: bridge